### PR TITLE
Implemented Slice OP.

### PR DESCRIPTION
**Pull request by goldgeisser**
Added utility function convertToTensor

### CODE REVIEW

**Comment by goldgeisser** [comment]
Added Slice OP implementation

**Comment by goldgeisser** [comment]
@yinghai @benbarsdell 
Could you please approve or at least address?  I have several PRs I intend to submit and this one is gating.

**Comment by bpinaya** [comment]
I had a related question when slicing in pytorch (for fcn) I'd do something like this:
```
score_pool4[:, :, 5:51, 5:87]
```
When the model is exported to onnx the result would be something like (visualization using Netron):
image

Since this really doesn't do any batch slicing or similar, in my own implementation just added a condition that would skip the Slices if `start` is 0 and `end` is MAX_INT, does this make sense? I'm getting some really innacurate results and wanted to get some feedback. I guess it's somehow related to this PR. Didn't know where else to post.

**Comment by kevinch-nv** [comment]
Closing based on new PR here: https://github.com/onnx/onnx-tensorrt/pull/101

**Pull request closed without merging**
