### PR TITLE
Use new TensorRT Python bindings

### PR DESCRIPTION
**Pull request by qiubit**
WIP, since still needs to be tested, and backend tests currently don't work

### CODE REVIEW

**Comment by yinghai** [comment]
@qiubit What's the status of the PR? Is it still WIP?

**Comment by bhack** [comment]
Any news?

**Comment by goldgeisser** [comment]
@yinghai I am going to take it from here. This gating some other PRs I need to submit (since I cannot test it with the new TensorRT 5)

**Comment by kevinch-nv** [comment]
Closing - Python bindings are now provided by TensorRT itself.

**Pull request closed without merging**
